server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: kvstore
  profiles:
    active: dev

# KV Store Configuration
kvstore:
  # Storage configuration
  storage:
    data-dir: ./data
    memtable:
      max-size: 100MB
      flush-threshold: 80MB
    sstable:
      max-size: 100MB
      merge-threshold: 5
    wal:
      enabled: true
      sync-interval: 1000  # 1 second in milliseconds
      max-size: 1GB
  
  # Compaction configuration
  compaction:
    enabled: false
    interval: 300000  # 5 minutes in milliseconds
    check-interval: 60000  # 1 minute in milliseconds
    max-duration: 300000  # 5 minutes in milliseconds
  
  # Raft configuration
  raft:
    enabled: true
    election-timeout: 5000  # 5 seconds in milliseconds
    heartbeat-interval: 1000  # 1 second in milliseconds
    cluster:
      nodes:
        - id: node1
          host: localhost
          port: 8081
        - id: node2
          host: localhost
          port: 8082
        - id: node3
          host: localhost
          port: 8083
  
  # gRPC configuration for inter-node communication
  grpc:
    enabled: true
    port: 9090
  
  # Hash ring configuration
  hash-ring:
    virtual-nodes-per-node: 150
    replication-factor: 3
  
  # Node configuration
  node:
    id: ${NODE_ID:node1}
    host: ${NODE_HOST:localhost}
    port: ${NODE_PORT:9090}

# Logging configuration
logging:
  level:
    com.moniepoint.kvstore: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/kvstore.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  server:
    port: 8081 